### ISSUE TITLE
Repo cleanup

### ISSUE THREAD

**Issue by njsmith** [python-trio/hip#155]
I think we should:

- [x] go through and delete all the legacy branches we aren't actively using (I think that's everything except: `bleach-spike`, `api-design`, and `disable-ci`?)
- [x] go through and rename all the existing tags from `<version>` to `urllib3/<version>` or similar – it might be handy to keep them around for historical purposes, but we're restarting the version numbering, so they shouldn't just be called `<version>`. Or maybe it doesn't matter and we should just delete them?
- [x] rename `bleach-spike` to `master`
- [x] switch the project settings to make `master` the default+protected branch

Am I missing anything? This all requires some fiddly+intrusive git stuff, so we want to do it soon, but we also want to do it right...

**Comment by pquentin** [comment]
You also want to remove the releases from GitHub: https://github.com/python-trio/hip/releases

**Comment by njsmith** [comment]
I think that's just another view of the tags? I'm not 100% sure.

**Comment by pquentin** [comment]
Oh right, I did not know about that. I think it's fine to delete tags and releases, it's not like urllib3/urllib3 is going away. I believe just renaming them would be confusing

**Comment by njsmith** [comment]
I deleted the tags, using:

```
for TAG in $(git tag); do git tag -d $TAG && git push origin :refs/tags/$TAG; done
```

(Kinda slow b/c it did ~45 separate pushes, but it worked.) And that does seem to have cleaned up the "releases" tab on github too.

**Comment by njsmith** [comment]
OK, I also deleted all the old stale branches (using [Github's convenient UI for this](https://github.com/python-trio/hip/branches)), and renamed `bleach-spike` → `master`.

**Comment by sethmlarson** [comment]
We're gonna have to cleanup the README as well. Lots of references to urllib3 abound!
