### ISSUE TITLE
Intermittent failures

### ISSUE THREAD

**Issue by pquentin** [python-trio/hip#183]
Okay so we're soon going to multiple backends, so all tests are going to be run many more times per build, so it's going to be even more important that they're reliable. I have kept putting this off, but I think it's important to be serious about it.

So I think I'm going to start listing failures here, to remember that I need to fix them. Usually the failures are simple timeouts issues where the timeout is not correctly chosen or applies to too many operations.

**Comment by pquentin** [comment]
TestSocketClosing.test_release_conn_param_is_respected_after_timeout_retry failed in https://travis-ci.org/python-trio/hip/jobs/619225273

**Comment by sethmlarson** [comment]
@pquentin We should probably close this in favor of #200?

**Comment by pquentin** [comment]
Ah yes good call let's keep #200 instead. Closing this one.
