### ISSUE TITLE
PoolManager(block=True) + trio.nursery causes EmptyPoolError

### ISSUE THREAD

**Issue by haolian9** [python-trio/hip#235]
I have wrote two test cases to reproduce the issue. (as you know, it requires trio, hip, pytest, pytest-trio to run)

And I expect `test_lock()` will not throw an EmptyPoolError exception.

```python
import ahip
import pytest
import trio


async def _routine(http):
    # copied from readme
    resp = await http.request(
        "GET", "http://httpbin.org/robots.txt", pool_timeout=3 + 10
    )

    assert resp.status == 200
    assert resp.data == b"User-agent: *\nDisallow: /deny\n"


async def test_nonblock():
    http = ahip.PoolManager(
        # connection pool kw
        timeout=3,
        retries=False,
        maxsize=1,
        block=False,
    )

    with http:
        await _routine(http)


async def test_block():
    http = ahip.PoolManager(
        # connection pool kw
        timeout=3,
        retries=False,
        maxsize=1,
        block=True,
    )

    with pytest.raises(ahip.exceptions.EmptyPoolError):
        with http:
            async with trio.open_nursery() as nursery:
                for _ in range(2):
                    nursery.start_soon(_routine, http)

```

---
updates:

* `pool_timeout` was added otherwise the program seems will block forever
* There are 2 tasks running in `test_block()`

**Comment by pquentin** [comment]
That's an interesting find. :) I'm not sure what's going on, this is probably not covered by the unit tests yet. Would you be interested to fix it?

Also, are you really using hip? It's not maintained, I'd suggest just using httpx instead if you're interested in Trio support.

**Comment by haolian9** [comment]
Oh, I will try httpx.

Possible caused by [ConnectionPool.pool.get(block=True)](https://github.com/python-trio/hip/blob/bd7eb05b7d0b6cb8efa43d86796b8557f03fd142/src/ahip/connectionpool.py#L299),  pool is the builtin queue and no `await`

**Comment by haolian9** [comment]
as last time i dig into the details, I found fixing this issue would introduce trio.memory_channel that replaces queue.Queue, I was heisitated whether should i  provider a fix, since hip says it also works on asyncio; and latter i was heared about anyio ...

anyway, I have found httpx more well maintained and more popular, and works perfect in my project. so I am closing this issue in my side.
